Some suggestion for improving the blog
valkey-io/valkey-io.github.io pull request #119
Opened 2024-09-01 01:34 UTC by madolson

### Description

While writing the Valkey 8.0 blogs, I had some minor gripes and thought I would try to present them in a PR and get some feedback.

1. On desktop, the real estate dedicated to authors is too much. I prefer the style of having authors at the end, so moved them down and aligned it horizontally.
2. The previous/next links are squished together. So now the right link is right adjusted. 
 
What it looks like now:

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/b885ccd9-13b9-45bd-b69f-7319c1bc3eb1">

### Issues Resolved

No issues, just thought I would throw it out here as a suggestion.

### Check List
- [X] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2024-09-01 01:41 UTC, PingXie approved these changes
fully agreed on both points. I don't know anything about .scss files so approving the high level ideas only.

2024-09-03 10:50 UTC, stockholmux requested changes
I put a few comments on the code itself.

As far as the idea, I can get behind this if this is what lots of folks want it, but the shorter lines were probably easier to read and more accessible.

The [WCAG 2.1](https://www.w3.org/WAI/WCAG21/Understanding/) states that there should be no more than 80 characters per line.


> For people with some reading or vision disabilities, long lines of text can become a significant barrier. They have trouble keeping their place and following the flow of text. Having a narrow block of text makes it easier for them to continue on to the next line in a block. Lines should not exceed 80 characters or glyphs (40 if CJK), where glyphs are the element of writing in the writing system for the text.


After the change, lines are 140-155 characters per line. Even before the change, it was often over 90. I will say that the site is probably far from meeting the WCAG 2.1 in many other areas, but I do think it's important to go towards these standards.

2024-09-03 10:50 UTC, stockholmux commented on sass/_valkey.scss
> +  .container img {
`.container img` is pretty broad. Every template uses `.container`, so I'd ideally would prefer it to be a more specific class.

That said, I don't *think* currently we have images that doesn't need to span the container and (eventually) we probably need to work on a better template making this all more/less obsolete, so I think it's fine for now.

2024-09-03 10:50 UTC, stockholmux commented on templates/blog-page.html
> +  <a style="float:right;" class="next" href="{{page.lower.permalink}}">{{page.lower.title}} &raquo; </a>
Inline styles are gauche, hard to maintain, and you can save a few bytes with cached CSS. 

For the same effect, you can revert it to the previous, and add `_valkey.scss`
```css
.next {
  float: right;
}
```

2024-09-03 23:19 UTC, madolson commented
> As far as the idea, I can get behind this if this is what lots of folks want it, but the shorter lines were probably easier to read and more accessible.

Hmm, I don't like the short lines, but you did present other data and now I don't know what to say. I think my main grep was that for code lines, like the ones in the bitnami blog, are pretty annoying to read with 80 lines. Generally I don't mind the 80 line length though. It does say "should", so it feels like we are allowed to ignore it.

2024-09-03 23:26 UTC, madolson commented
Honestly, the 80 character isn't really a hill I want to die on, and it seems like the docs and commands use it. I really just didn't like the clutter with the authors at the top. The latest version keeps the width and is much cleaner.

2024-09-03 23:28 UTC, madolson commented
<img width="682" alt="image" src="https://github.com/user-attachments/assets/cd82fb68-b282-4bbc-8cca-c6efe0a26516">
The next/prev is still really close, not sure there is much to do about that without putting them on different lines.

2024-09-04 06:50 UTC, stockholmux commented
> The next/prev is still really close, not sure there is much to do about that without putting them on different lines.

I agree, that's messy.

What if we did something like this (of course with the writer bios at the bottom).

<img width="847" alt="Screenshot 2024-09-04 at 8 44 51 AM" src="https://github.com/user-attachments/assets/676d42fb-7f1e-4cc9-aa47-2191e8bc4a8e">

I was able to mock it up in dev tools by altering the styles for next/prev to something like this:
```css
    display: inline-block;
    float: right;
    max-width: 40%;
    text-align: right;
```

(the other side is slightly different, but you can see the approach)

It gets complicated because we need to undo this on mobile or it will be like 3 characters per line on the next/prev. I'm glad to do this, but maybe we should make an issue and I can just implement it under a different PR.

2024-09-04 18:04 UTC, stockholmux reviewed
LGTM

2024-09-04 18:09 UTC, merged