feat: Update the about page to include a brief history of the project.
valkey-io/valkey-io.github.io pull request #18
Opened 2024-04-09 03:40 UTC by Laphatize

### Description

I included a brief history of the project in the /about section of the website.

Screenshot showcasing this:
![Screenshot of Page](https://i.ibb.co/brsrXJW/Screenshot-2024-04-08-at-11-38-00-PM.png "Screenshot of Page")

### Issues Resolved

Addresses a point mentioned in https://github.com/valkey-io/valkey-website/issues/13.
>  Content: About Page (/about/) MVP: 1 paragraph that describes the history of the project

### Check List
- [X] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

2024-04-09 18:56 UTC, stockholmux requested changes
This is fantastic work @Laphatize!

I'll accept it with the changes suggested, but if you have time convert it from an HTML file to markdown and make each sentence one line.

2024-04-09 18:56 UTC, stockholmux commented on about/index.html
> +Valkey is an open source fork of Redis, created in March 2023 after Redis announced a change to a more <a href="https://redis.io/blog/redis-adopts-dual-source-available-licensing/">restrictive licens
- There are a lot of opinions about the word 'fork'. Maybe: `Valkey is a open source continuation of Redis created`
- `more restrictive license` change to `non-open source license`.

2024-04-10 02:43 UTC, Laphatize commented
Should be all taken care of. Sorry it took me so long - was swamped with homework.

2024-04-10 13:42 UTC, stockholmux approved these changes
LGTM

2024-04-10 18:10 UTC, merged

2024-04-10 18:10 UTC, stockholmux commented
Congrats @Laphatize! Glad to have you as a contributor.