Replaced logo with wordmark SVG, added artist credit
valkey-io/valkey-io.github.io pull request #63
Opened 2024-05-05 18:01 UTC by kris-ms

### Description

Replaces plain text logotype with SVG provided in assets folder. (/assets/img/Valkey-wordmark.svg)
Credits the creator of the new logo design.
 
### Issues Resolved

Closes #28 

By submitting this pull request, I confirm that my contribution is made under the terms of the BSD-3-Clause License.

Cheers, please let me know if there are any issues!

2024-05-07 18:53 UTC, stockholmux requested changes
This is awesome! Thanks for the contribution. I have change in the review and after that it LGTM.

2024-05-07 18:53 UTC, stockholmux commented on _layouts/default.html
> +            <img src="/assets/img/Valkey-wordmark.svg" alt="Valkey Logo" width="180px" />
For now this should probably just have the logo + the opensans "Valkey"

The wordmark was created before a bunch of stuff was settled: it's Valkey not ValKey and the font's hasn't been officially picked yet. 

I'd actually be okay if removed the wordmark file was removed for now.

2024-05-08 10:23 UTC, kris-ms commented
> This is awesome! Thanks for the contribution. I have change in the review and after that it LGTM.

Appreciate the review, changes attached, cheers!

2024-05-09 13:49 UTC, stockholmux approved these changes

2024-05-09 13:49 UTC, merged

2024-05-09 14:29 UTC, stockholmux commented
@kris-ms Your work is live on Valkey.io 🎉